### PR TITLE
Added feature to download attachments.

### PR DESCRIPTION
**Pull request by lazartravica**
Attachments will now be automatically downloaded for each board.

Example:
Attachments of board `Product ideas` of organization `ACME` will be saved to `$path/trello-org-ACME-Product-ideas/<attachment-name>`

### CODE REVIEW

**Comment by EHJ-52n** [comment]
@mattab What blocks the merge of this PR?

**Comment by mattab** [comment]
Hi @lazartravica thanks for the pull request!

@EHJ-52n did you test this PR and does it work as expected for you?

**Comment by EHJ-52n** [comment]
@mattab  @lazartravica 

I receive one error during the download of attachments:

```
PHP Warning:  file_put_contents(/home/user/data/trello-backup//trello-org-ACME-board-my-board.json): failed to open stream: Permission denied in /home/user/trello-backup/trello-backup.php on line 109
PHP Stack trace:
PHP   1. {main}() /home/user/trello-backup/trello-backup.php:0
PHP   2. file_put_contents() /home/user/trello-backup/trello-backup.php:109
```

For all other boards, the files are downloaded and stored in a folder with the board name, same as the json file. Re-run results in the same error.

**Comment by lazartravica** [comment]
@EHJ-52n it seems that this error does not occur during the download of attachments, but rather during the download of the boards themselves. From what I can see a trailing slash in your $path config variable can be a problem. 

Can you please post the full output?

**Comment by mattab** [comment]
@lazartravica fixed in #24 with new `$path` config variable now set by default to the  ./trello-backup directory

**Comment by EHJ-52n** [comment]
@lazartravica you are right. I have a trailing slash in the ```config.php```.

@mattab Could you please clarify, that the trailing slash is optional and will not break, if being removed. Maybe, you can add a sentence of documentation in the ```config.example.php```.

**Pull request merged**
